package.json
The repo/bugs url/homepage location is incorrect.
=> fix: correct repo location

CHANGELOG.md, package-lock.json, package.json
Main changes in this release:
- feat(reporters): add some reporters that can be used to validate the model, and show errors found
=> release: bump package version to v0.0.3

CHANGELOG.md, package-lock.json, package.json
Main changes in this release:
- Fix #35
- Update dependencies #37
=> release: bump package version to v0.0.4

package-lock.json, package.json, tests/__snapshots__/dsl.test.ts.snap, tests/__snapshots__/index.test.ts.snap
=> chore(deps): update dependencies

.github/dependabot.yaml, CHANGELOG.md, package-lock.json, package.json
=> release: bump package version to v0.0.5

CHANGELOG.md, package-lock.json, package.json
Bump version to 0.0.6 and update dev dependency
N/A
=> release: bump package version to v0.0.6

README.md
Adds link to several parsers contributed by community members
=> chore: link to community parsers

src/check-dsl.ts, src/openfga.ne, src/parse-dsl.ts, src/reporters.ts, tests/data/model-validation.ts, tests/dsl-validation.test.ts
Refactor checkDSL and add in validation test infrastucture in preparation for additional validation for list object.
=> chore: refactor checkDSL and add in validation infrastucture

CHANGELOG.md, package-lock.json, package.json
=> release(v0.0.7): update changelog

CHANGELOG.md, package-lock.json, package.json
Bump version number and update changelog for v0.0.8
=> release(v0.0.8): update changelog

CHANGELOG.md, package-lock.json, package.json
changes:
- feat(editor-support): expose auto-completion for monaco (openfga/syntax-transformer#90)
- feat(editor-support): expose syntax highlighting and tokenization for monaco and prism (openfga/syntax-transformer#90)
- chore(deps): bump dev dependencies
=> release: v0.0.9

CHANGELOG.md, README.md, package-lock.json, package.json
=> fix: add yargs to list of deps

src/syntax-highlighters/prism/language-definition.ts
closes openfga/syntax-transformer#116
=> fix: do not use regex lookbehind

CHANGELOG.md, package-lock.json, package.json
=> release: v0.0.14

src/constants/default-schema-version.ts, src/constants/index.ts, src/transformer/api-to-friendly.ts, src/transformer/friendly-to-api.ts, src/validator/check-dsl.ts, src/validator/reporters.ts, src/validator/validation-error.ts, tests/data/test-models.ts
To be merged March 31st
- Closes #125
- https://openfga.dev/docs/modeling/migrating/migrating-schema-1-1#deprecation-timeline
=> feat!: default to schema v1.1

CHANGELOG.md, package-lock.json, package.json
To be merged on April 31st
- Blocked by: https://github.com/openfga/syntax-transformer/pull/122
- https://openfga.dev/docs/modeling/migrating/migrating-schema-1-1#deprecation-timeline
=> release: v0.1.0

package-lock.json, package.json, src/parser/openfga.ne, src/validator/check-dsl.ts, src/validator/reporters.ts, tests/data/model-validation.ts
1. Allow self references in some types
2. Prevent invalid model that may introduce infinite loop
1. Close https://github.com/openfga/syntax-transformer/issues/133
2. Implement syntax transformer changes that prevent invalid model as pointed out in  https://github.com/openfga/openfga/security/advisories/GHSA-hr9r-8phq-5x8j
=> feat: extend self ref

CHANGELOG.md, package-lock.json, package.json
=> release: v0.1.3 with fixes and changes to validation

.eslintrc.js, package-lock.json, package.json, src/syntax-highlighters/monaco/providers/code-actions.ts, src/syntax-highlighters/prism/language-definition.ts, src/transformer/api-to-friendly.ts, src/utilities/graphs/model-graph.ts, src/validator/validation-error.ts, tests/data/model-validation.ts
=> fix: language definition for PrismJS

.github/dependabot.yaml, .github/workflows/main.yaml
=> chore: dependabot grouped deps + github actions pinned deps

.github/workflows/main.yaml, .gitmodules, .prettierignore, package-lock.json, package.json, src/index.ts
* Git submodule used to add language as a dependency
* `checkDSL` & `CMD` commands updated to use `validateDsl` from `language`
* Removed outdated test suite, as all but the 1.0 specific tests have been migrated
* Fixed eslint duplicate config issue
* Excluded `language` from prettier & madge as a temporary fix to checking failures for submodule
- closes https://github.com/openfga/syntax-transformer/issues/141
=> feat: Add language errors and vadlidateDsl

CHANGELOG.md, package-lock.json, package.json
=> release: v0.1.4

CHANGELOG.md, package-lock.json, package.json, src/index.ts
=> release(v0.1.5): fix linking language

.github/workflows/main.yaml, .gitmodules, .prettierignore, CHANGELOG.md, package-lock.json, package.json, src/index.ts
Remove the language submodule
- closes #156
=> fix: remove language (v0.1.6)

.editorconfig, .prettierrc, package-lock.json, package.json, src/samples/index.ts, src/theme/index.ts, src/tools/monaco/language-definition.ts, src/tools/monaco/providers/completion.ts, src/utilities/graphs/index.ts, src/utilities/graphs/model-graph.ts, src/utilities/graphs/related-users-graph.ts, tests/data/test-models.ts
=> chore(deps): upgrade dependencies

CHANGELOG.md, package-lock.json, package.json
=> release(v0.2.0-beta.2): with conditions support

CHANGELOG.md, package-lock.json, package.json
* Condition support for prism
* Fixes for grammar for monaco
* Needs testing in the playground and docs site
=> release(v0.2.0-beta.3): conditions for prism + monaco grammar fixes

.github/CODEOWNERS
=> chore: change owner team

CHANGELOG.md, package-lock.json, package.json, src/utilities/graphs/related-users-graph.ts, tests/__snapshots__/dsl.test.ts.snap, tests/data/model-validation.ts
=> release(v0.2.0-beta.4): with dependency updates

src/tools/monaco/language-definition.ts
=> fix: comment grammar

CHANGELOG.md, package-lock.json, package.json, tests/data/model-validation.ts
=> release: v0.2.0-beta.5

CHANGELOG.md, package-lock.json, package.json
Release to include the fix for monaco validation so that we can bubble up to dashboard
=> release: v0.2.0-beta.6

.github/CODEOWNERS
=> chore: add dx as approver for README

CHANGELOG.md, package-lock.json, package.json
=> release: v0.2.0 beta.7 

CHANGELOG.md, package-lock.json, package.json
=> release: 0.2.0-beta.8

CHANGELOG.md, package-lock.json, package.json
=> release: v0.2.0-beta.9

package-lock.json, package.json
=> chore(deps): bump deps

package-lock.json, package.json, src/constants/schema-version.ts, src/tools/monaco/providers/code-actions.ts, src/tools/monaco/providers/completion.ts
=> feat(utils): update schema version for modular models

CHANGELOG.md
=> release: v0.2.0-beta.10

CHANGELOG.md, package-lock.json, package.json
=> chore: bump up package version

.npm-upgrade.json, CHANGELOG.md, package-lock.json, package.json, tests/data/model-validation.ts
=> release: v0.2.0-beta.11

.github/workflows/main.yaml, CHANGELOG.md, package-lock.json, package.json
=> chore(deps): upgrade dependencies & drop support for node@14

.github/SECURITY-INSIGHTS.yml
Automated update of SECURITY-INSIGHTS.yml file
=> chore: update SECURITY-INSIGHTS
