src/check-dsl.ts, src/index.ts, src/reporters.ts, tests/__snapshots__/dsl.test.ts.snap, tests/dsl.test.ts
These reporters can be used to report errors in the syntax.
They are currently in use as the building block for validation in the [Auth0 FGA Playground](https://play.fga.dev).
=> feat: add dsl checker

src/check-dsl.ts, tests/__snapshots__/dsl.test.ts.snap, tests/data/test-models.ts, tests/dsl.test.ts
We were incorrectly detecting relations that start with `as` as the end boundary of relations instead of the keyword `as`. Leading to the relation in certain cases to be improperly detected.
E.g. when the definition is: `define access as subscriber from associated_plan`, the detected relation by the reporter was `access as subscriber from`.
Resolves https://github.com/openfga/syntax-transformer/issues/35
=> fix(check-dsl): incorrect parsing of relations starting with `as`

package-lock.json, package.json, src/check-dsl.ts, src/friendly-to-api.ts, src/keywords.ts, src/parse-dsl.ts, src/reporters.ts, tests/__snapshots__/dsl.test.ts.snap, tests/dsl.test.ts
Correct DSL checker and update test snapshot to correct expected result.  In addition, add test to ensure dsl checker able to detect the right error line with empty line in DSL.
Close https://github.com/openfga/syntax-transformer/issues/55
=> fix: resolve failing issues with checkDSL validation on the new grammar

src/check-dsl.ts, src/reporters.ts, tests/__snapshots__/dsl.test.ts.snap
Correct column identified in self-ref error
Close https://github.com/openfga/syntax-transformer/issues/62
=> fix: correct column identified in self-ref error

src/api-to-friendly.ts, tests/api-to-friendly.test.ts
Identify partial model as type is not set instead of using relations.
Close https://github.com/openfga/syntax-transformer/issues/65
=> fix: handle case if relations not defined in full model

.gitignore, src/check-dsl.ts, tests/__snapshots__/dsl.test.ts.snap, tests/dsl.test.ts
It is ok for the same relation in the computedUserset of the "from" clause. For example,
```
define subscriber as subscriber from associated_plan
```
Close https://github.com/openfga/syntax-transformer/issues/69
=> fix: allow same relation in computedUserset of from clause

src/api-to-friendly.ts, src/check-dsl.ts, src/friendly-to-api.ts, src/openfga.ne, src/parse-dsl.ts, tests/__snapshots__/dsl.test.ts.snap, tests/__snapshots__/index.test.ts.snap, tests/data/test-models.ts
Support types when defining relations.
new DSL:
```
type document
relations
define viewer: [user, team#member] as self
```
new parser output:
- https://github.com/openfga/rfcs/pull/7/
=> feat: allow types for relations

src/openfga.ne, src/parse-dsl.ts, tests/__snapshots__/index.test.ts.snap, tests/dsl.test.ts, tests/index.test.ts
We had some issues in our grammar causing infinite loops when trying to parse, especially when extraneous spaces or newlines were found.
We still have some issues with parsing comments, but it has been limited.
Closes #77
=> fix(parse-dsl): fix issue with infinite loops triggered when parsing some models

src/check-dsl.ts, src/default-regex.ts, src/reporters.ts, tests/data/model-validation.ts, tests/dsl.test.ts
Allow specifying regex rule for type and relation name validation
=> feat: validation rule for type and relation name

src/check-dsl.ts, tests/data/model-validation.ts
Handle case where same relation name is used for multiple types.
Close https://github.com/openfga/syntax-transformer/issues/82
=> fix: correct error location in model 1.0

src/api-to-friendly.ts, src/check-dsl.ts, src/indent-dsl.ts, src/keywords.ts, src/openfga.ne, src/reporters.ts, tests/data/model-validation.ts, tests/data/test-models.ts, tests/indent-dsl.test.ts
Allow specifying schema in DSL.  For model schama version != 1.0, we will also convert it back from JSON to DSL.  For schema version 1.0, we will omit converting schama version as by default it is 1.0.  It is expected that later on we will also list out the version in the case of 1.0
- Closes #81
=> feat: specify schema version in DSL

tests/data/model-validation.ts
The functionality is already there, but we want to add unit test to ensure that `this` cannot be use as part of union/intersection.  Note that if `this` is used as type, it should already been flagged in test "invalid relation name for this".
Close https://github.com/openfga/syntax-transformer/issues/33
=> chore: add test to ensure this cannot be used in union/intersection

README.md
update README to correct broken HTTP API links
=> fix: update README to correct broken links

src/indent-dsl.ts
This includes tokens from Keywords constants instead of inline strings in the indenting script.
N/A
=> Leverage Keywords namespace for indentation tokens

src/api-to-friendly.ts, src/check-dsl.ts, src/openfga.ne, src/parse-dsl.ts, src/reporters.ts, tests/__snapshots__/dsl.test.ts.snap, tests/data/model-validation.ts, tests/data/test-models.ts, tests/dsl.test.ts
1. For model 1.1, do not use 'as self'.  Instead, always use ':'
2. Validate to ensure 1.0 still use 'as self' and contains no ':'
Close https://github.com/openfga/syntax-transformer/issues/92
=> feat: remove as self in model 1.1

package-lock.json, package.json, src/api-to-friendly.ts, src/check-dsl.ts, src/friendly-to-api.ts, src/openfga.ne, src/reporters.ts, tests/data/model-validation.ts, tests/data/test-models.ts, tests/dsl.test.ts
Implement wildcard type restriction for DSL.
Close https://github.com/openfga/syntax-transformer/issues/93
=> feat: wildcard type restriction

package-lock.json, package.json
Override to fix severe vulnerability in json5 package
https://github.com/import-js/eslint-plugin-import/issues/2632
=> chore: bump packages and override json5

src/validator/check-dsl.ts, tests/data/model-validation.ts
Relax model validation such that TTU relation is valid as long as one of the child has such relation
Close https://github.com/openfga/syntax-transformer/issues/113
=> fix: allow ttu relation as long as one of the child has such relation

src/parser/openfga.ne, tests/__snapshots__/dsl.test.ts.snap, tests/data/model-validation.ts, tests/dsl.test.ts, tests/index.test.ts
If the model schema is not defined in DSL, we should not assume it is 1.0
=> fix: DSL should not allow schema version not specified

src/tools/monaco/language-definition.ts
There is more work that can be done to clean up this language definition, but for now I've done the following:
* Re-organize grammar to leverage state while parsing `[ ]` content
* Pulled out `cel_symbols` into their own state while parsing `{ }` content
* Remove redundant declarations
=> fix: restrictions grammar

src/tools/monaco/validate.ts
It's possible for an error returned from the `validateDSL` method in `language` to return no metadata ([1](https://github.com/openfga/language/blob/d4c79707596a3fd8548ebd63c32630d57c1a3b0f/pkg/js/errors.ts#L75), [2](https://github.com/openfga/language/blob/d4c79707596a3fd8548ebd63c32630d57c1a3b0f/pkg/js/errors.ts#L75)), based on documentation/the source code from ANTRL this would indicate that the error arose from the lexer but unfortunately I've not been able to come up with a case where I can reproduce this to write a test from.
That said, based on the error shown in Sentry and the surrounding code this is a fairly certain fix for the issue.
=> fix(moncaco/validate): handle metadata being undefined

package-lock.json, package.json, src/tools/monaco/validate.ts
Updates the language package and then refactors validateDSL to allow modular models to fail validation in the editor.
=> chore: update language dep
